// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8HalOibRXoc0RWm-15mxKiKHX4wIOjDM',
    appId: '1:123538185487:web:2db4483b311d7bee20327a',
    messagingSenderId: '123538185487',
    projectId: 'doctorappointmentapp-d4e0e',
    authDomain: 'doctorappointmentapp-d4e0e.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-d4e0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM5Z_CzD4EqEapfFDmV1e8eGTwcltwpX0',
    appId: '1:123538185487:android:0c801ab0a62e9b3620327a',
    messagingSenderId: '123538185487',
    projectId: 'doctorappointmentapp-d4e0e',
    storageBucket: 'doctorappointmentapp-d4e0e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8HalOibRXoc0RWm-15mxKiKHX4wIOjDM',
    appId: '1:123538185487:web:24e12f5e41de7e8f20327a',
    messagingSenderId: '123538185487',
    projectId: 'doctorappointmentapp-d4e0e',
    authDomain: 'doctorappointmentapp-d4e0e.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-d4e0e.firebasestorage.app',
  );
}
